version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
      timezone: Asia/Jakarta
    open-pull-requests-limit: 100
    ignore:
      - dependency-name: webpack
        versions:
          - 5.34.0
      - dependency-name: buefy
        versions:
          - 0.9.7
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
      timezone: Asia/Jakarta
    open-pull-requests-limit: 100
