language: ruby
rvm:
  - 2.6
node_js:
  - "12"

before_install:
  - nvm install node
  - nvm use node
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
  - export PATH="$HOME/.yarn/bin:$PATH"
  - gem update --system
  - gem install bundler

before_script:
 - yarn
 - yarn build

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script:
  - yarn test
  - bundle exec jekyll build
# - bundle exec htmlproofer ./_site --disable-external

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

deploy:
  provider: pages
  local-dir: ./_site
  target-branch: master
  email: bervianto.leo@gmail.com
  name: Bervianto Leo Pratama
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: development

cache:
  - bundler # caching bundler gem packages will speed up build
  - yarn

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false
