---
title: Bervianto Leo Pratama
timezone: Asia/Jakarta
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: bervianto.leo@gmail.com
description: Personal Website of Bervianto Leo Pratama
baseurl: ''
url: ''
keywords:
- Android
- Mobile
- Web
excerpt_separator: "<!--more-->"
permalink: "/articles/:year-:month/:title"
plugins:
- jekyll-paginate-v2
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
owner:
  name: Bervianto Leo Pratama
  avatar: bervianto.jpg
  job: Mobile & Web Developer
  bio: Backend & frontend is me.
  email: bervianto.leo@gmail.com
  disqus-shortname: berviantoleopratama
  twitter: berviantoleo
  facebook: bervianto.leo
  google:
    plus: BerviantoLeoPratama
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: berviantoleo
  stackoverflow: 6948591/bervianto-leo-pratama
  linkedin: bervianto-leo-pratama
  xing: 
  instagram: bervianto.leo
  lastfm: berviantoleo
  tumblr: 
  pinterest: berviantoleo
  foursquare: 
  steam: cyber-name
  dribbble: 
  youtube: BerviantoLeoPratama
  soundcloud: bervianto-leo-pratama
  weibo: 
  flickr: 
  codepen: 
  telegram: berviantoleo
exclude:
- old/
- src/
# - Gemfile
- Gemfile.lock
- node_modules/
- .sass-cache
- lib/
- package-lock.json
- package.json
- webpack.config.js
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set

pagination:
  enabled: false
  debug: false
  collection: posts
  per_page: 10
  permalink: page/:num/
  title: ":title - page :num"
  limit: 0
  sort_field: date
  sort_reverse: true
  category: posts
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2
  extension: html
  indexpage: index
