#
###################################
# Site wide configuration
####################################
#
title: Bervianto Leo Pratama Profile
email: bervianto.leo@gmail.com
description: A simple and awesome blog theme powered by jekyll.
url: https://berviantoleo.github.io # the base hostname & protocol for your site


#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Jakarta
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Bervianto Leo Pratama
  avatar: bervianto.jpg
  job: "Mobile & Web Developer"
  bio: "Backend & frontend is me."
  email: bervianto.leo@gmail.com
  disqus-shortname: berviantoleopratama
  twitter: berviantoleo #username
  facebook: bervianto.leo #username
  google:
    plus: BerviantoLeoPratama #username
    analytics: 
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: berviantoleo #username
  stackoverflow: 6948591/bervianto-leo-pratama #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: bervianto-leo-pratama #username
  xing: #username
  instagram: bervianto.leo #username
  lastfm: berviantoleo #username
  tumblr: #username
  pinterest: berviantoleo #username
  foursquare: #username
  steam: cyber-name #username
  dribbble: #username
  youtube: BerviantoLeoPratama #username
  soundcloud: bervianto-leo-pratama #username
  weibo: #username
  flickr: #username
  codepen: #username
