---
title: Bervianto Leo Pratama Profile
timezone: Asia/Jakarta
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: bervianto.leo@gmail.com
description: A simple and awesome blog theme powered by jekyll.
url: https://berviantoleo.github.io
keywords: ["Android", "Mobile", "Web"]
markdown: kramdown
highlighter: rouge
excerpt_separator: "<!--more-->"
permalink: "/articles/:year-:month/:title"
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
owner:
  name: Bervianto Leo Pratama
  avatar: bervianto.jpg
  job: Mobile & Web Developer
  bio: Backend & frontend is me.
  email: bervianto.leo@gmail.com
  disqus-shortname: berviantoleopratama
  twitter: berviantoleo
  facebook: bervianto.leo
  google:
    plus: BerviantoLeoPratama
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: berviantoleo
  stackoverflow: 6948591/bervianto-leo-pratama
  linkedin: bervianto-leo-pratama
  xing: 
  instagram: bervianto.leo
  lastfm: berviantoleo
  tumblr: 
  pinterest: berviantoleo
  foursquare: 
  steam: cyber-name
  dribbble: 
  youtube: BerviantoLeoPratama
  soundcloud: bervianto-leo-pratama
  weibo: 
  flickr: 
  codepen: 
  telegram: berviantoleo
