name: Build Site
on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn lint, build and test
        run: |
          yarn
          yarn lint
          yarn build
          yarn test
        env:
          CI: true
      - name: Build the site in the jekyll/builder container
        if: ${{ matrix.node-version == '14.x'}}
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/jekyll:3 /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
      - name: Test Build the Custom docker
        if: ${{ matrix.node-version == '14.x'}}
        run: |
          docker build . -t jekyll-custom
      - name: Deploy 🚀
        if: ${{ github.event_name == 'push' && matrix.node-version == '14.x'}}
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: _site # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
