name: Build Site
on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn Install
        run: yarn --frozen-lockfile
      - name: Lint
        run: yarn lint
      - name: Yarn build and test
        run: |
          yarn build
          yarn test
      - name: Build the site in the jekyll/builder container
        if: ${{ matrix.node-version == '14.x'}}
        run: |
          docker run --rm \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/jekyll:3 /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
      - name: Deploy 🚀
        if: ${{ github.event_name == 'push' && matrix.node-version == '14.x'}}
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          BRANCH: master # The branch the action should deploy to.
          FOLDER: _site # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
  docker-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Test Build the Custom docker
        run: |
          docker build . -t jekyll-custom
          docker run --name jekyll-server -d -p 80:80 jekyll-custom nginx -g 'daemon off;'
          docker ps -a
          sleep 10
          curl --connect-timeout 10 \
            --max-time 100 \
            --retry 5 \
            --retry-delay 5 \
            --retry-max-time 150 \
            'http://localhost'
          docker stop jekyll-server
          docker rm jekyll-server

